[[language]]
name = "rust"
auto-format = true

[[language]]
name = "python"
auto-format = true
formatter = { command = "black", args = ["--stdin"] }

[[language]]
name = "javascript"
auto-format = true
formatter = { command = "prettier", args = ["--stdin"] }

[[language]]
name = "typescript"
auto-format = true
formatter = { command = "prettier", args = ["--stdin"] }

[[language]]
name = "css"
auto-format = true
formatter = { command = "prettier", args = ["--stdin"] }

[[language]]
name = "html"
auto-format = true
formatter = { command = "prettier", args = ["--stdin"] }

